I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 17, in script
    show alex reverse:
Exception: Image 'alex' does not accept attributes 'reverse'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 17, in script
    show alex reverse:
  File "D:\Program Files\Я не гей (renpy)\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\Program Files\Я не гей (renpy)\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "D:\Program Files\Я не гей (renpy)\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\Program Files\Я не гей (renpy)\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "D:\Program Files\Я не гей (renpy)\renpy-8.1.3-sdk\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "D:\Program Files\Я не гей (renpy)\renpy-8.1.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'alex' does not accept attributes 'reverse'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
OPD_game 1.0
Mon Nov 20 02:10:04 2023
